
# This is an example `supabase/config.toml` file
# Visit the docs to see full annotations: 
# https://supabase.com/docs/guides/functions/config

[functions.delete-user]
verify_jwt = true

[functions.sync-users]
verify_jwt = true
