// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yniffahoakkkkfovzgux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluaWZmYWhvYWtra2tmb3Z6Z3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjcwOTcsImV4cCI6MjA2Mjk0MzA5N30.mCytghwX0KLeR-j3ue3fLL-hygUauyk_7Hb4Npi6aIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);