
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '../../types/supabase';

const SUPABASE_URL = "https://oyydsjvmtzilfvdzyupw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95eWRzanZtdHppbGZ2ZHp5dXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDk5NDEsImV4cCI6MjA1OTgyNTk0MX0.VgKE_f8pc0L21MGQe03K5tWmPJoAaWwRyQ7c8bb-y0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
