// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyvjtczkihdncxvsjdrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5dmp0Y3praWhkbmN4dnNqZHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDA3NDYsImV4cCI6MjA1ODA3Njc0Nn0.kjfHAUhtjbuTQ6lclGaR-Oq2GLGgg-q3bTOi-sRi8po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);